
# https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md

service: da-GlobalDemandSheets

plugins:
  - serverless-aws-alias

provider:
  name: aws
  account: ${opt:account, '002584813484'}
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-west-2'}
  versionFunctions: true
  role: arn:aws:iam::${self:provider.account}:role/${self:service}-${self:provider.stage}-role
  deploymentBucket: em-serverless-apps-${self:provider.region}-${self:provider.account}
  memorySize: 128
  timeout: 900
  logRetentionInDays: 14
  tags:
    Name: da-GlobalDemandSheetsUpdater
    Team: data-analytics
    TeamCode: da
    Project: ${self:service}
    Application: ${self:service}
    Environment: ${self:provider.stage}
    Tenants: all
    BilledTeam: data-analytics
  vpc:
    subnetIds:
      - subnet-b05fbed4
      - subnet-27ea0f51
      - subnet-7fa89926
    securityGroupIds:
      - sg-3c509e5b
      - sg-b232b8d5

package:
  individually: true
  exclude:
    - "*"
    - ".*/**"
    - "config/*"
  include:
    - "package.json"
    - "index.js"

functions:
  updater:
    handler: index.handler
    description: Description here
    environment: ${file(env.yml)}
    layers:
      - ${cf:node-everymundo-packages-layer.LibLambdaLayerQualifiedArn}
      - ${cf:node-googleapis-39-layer.LibLambdaLayerQualifiedArn}
      - ${cf:node-pg-layer.LibLambdaLayerQualifiedArn}
    events:
      - schedule:
          rate: cron(30 20 ? * * *)
          name: runs-every-day-at-8_30pm-UTC
          description: 'Runs every day at 8:30 pm (EST)'
    reservedConcurrency: 1

